import 'server-only';
import { getPrisma } from '@/lib/db';

export const sessionStatuses = ['OPEN','FULL','COMING_SOON','HIDDEN'] as const;
export type SessionStatus = typeof sessionStatuses[number];

const baseTrainings = [
 {id:'seed-aps',slug:'aps',name:'APS',title:'Agent de Prévention et de Sécurité',category:'sécurité',description:'',pageUrl:'/formations-securite/aps',isActive:true,createdAt:new Date(),updatedAt:new Date()},
 {id:'seed-ssiap-1',slug:'ssiap-1',name:'SSIAP 1',title:'Service de Sécurité Incendie et d’Assistance à Personnes',category:'sécurité',description:'',pageUrl:'/formations-securite/ssiap-1',isActive:true,createdAt:new Date(),updatedAt:new Date()},
 {id:'seed-a3p-apr',slug:'a3p-apr',name:'A3P',title:'Agent de protection physique des personnes',category:'sécurité privée',description:'',pageUrl:'/formations-securite/a3p-apr',isActive:true,createdAt:new Date(),updatedAt:new Date()},
 {id:'seed-bts-mos',slug:'bts-mos',name:'BTS MOS',title:'Management Opérationnel de la Sécurité',category:'bts',description:'',pageUrl:'/bts/mos',isActive:true,createdAt:new Date(),updatedAt:new Date()},
 {id:'seed-bts-mco',slug:'bts-mco',name:'BTS MCO',title:'Management Commercial Opérationnel',category:'bts',description:'',pageUrl:'/bts/mco',isActive:true,createdAt:new Date(),updatedAt:new Date()},
 {id:'seed-vtc',slug:'vtc',name:'VTC',title:'Chauffeur VTC',category:'vtc',description:'',pageUrl:'/formations-vtc',isActive:true,createdAt:new Date(),updatedAt:new Date()},
 {id:'seed-desp-dssp',slug:'desp-dssp',name:'DESP / DSSP',title:'Dirigeant d’entreprise de sécurité privée',category:'direction',description:'',pageUrl:'/formations-securite/desp',isActive:true,createdAt:new Date(),updatedAt:new Date()},
];
const baseSessions = [{id:'seed-a3p-septembre-2026',trainingId:'seed-a3p-apr',training:baseTrainings[2],title:'Session A3P septembre 2026',startDate:new Date('2026-09-01'),endDate:new Date('2026-10-27'),examDate:new Date('2026-10-28'),priceCents:420000,priceLabel:'4 200 €',location:'Puget-sur-Argens / Côte d’Azur',status:'OPEN',seatsTotal:null,seatsLeft:4,showSeatsLeft:true,durationLabel:'327 heures',registrationUrl:'/formations-securite/a3p-apr',fundingNotes:'Financement possible selon votre situation : CPF, France Travail ou financement personnel à vérifier avec l’équipe.',publicNotes:'Formation de 327 heures, hébergement collectif possible sur réservation.',internalNotes:'',sortOrder:0,isHighlighted:true,createdAt:new Date(),updatedAt:new Date()},
{id:'seed-a3p-novembre-2026',trainingId:'seed-a3p-apr',training:baseTrainings[2],title:'Session A3P novembre 2026',startDate:new Date('2026-11-09'),endDate:new Date('2027-01-19'),examDate:new Date('2027-01-20'),priceCents:420000,priceLabel:'4 200 €',location:'Puget-sur-Argens / Côte d’Azur',status:'OPEN',seatsTotal:null,seatsLeft:null,showSeatsLeft:true,durationLabel:'327 heures',registrationUrl:'/formations-securite/a3p-apr',fundingNotes:'Financement possible selon votre situation : CPF, France Travail ou financement personnel à vérifier avec l’équipe.',publicNotes:'Formation de 327 heures, hébergement collectif possible sur réservation.',internalNotes:'',sortOrder:1,isHighlighted:false,createdAt:new Date(),updatedAt:new Date()},
{id:'seed-ssiap-octobre-2026',trainingId:'seed-ssiap-1',training:baseTrainings[1],title:'Session SSIAP 1 octobre 2026',startDate:new Date('2026-10-12'),endDate:new Date('2026-10-27'),examDate:new Date('2026-10-28'),priceCents:98000,priceLabel:'980 €',location:'Puget-sur-Argens',status:'OPEN',seatsTotal:12,seatsLeft:12,showSeatsLeft:true,durationLabel:'67 heures minimum hors examen et déplacements',registrationUrl:'/contact',fundingNotes:'Financement à étudier selon votre situation : CPF si offre active publiée, France Travail, employeur/OPCO ou financement personnel.',publicNotes:'Option SST administrable selon votre secourisme détenu.',internalNotes:'optionSST: disponible',sortOrder:0,isHighlighted:true,createdAt:new Date(),updatedAt:new Date()},
{id:'seed-aps-septembre-2026',trainingId:'seed-aps',training:baseTrainings[0],title:'Session APS septembre 2026',startDate:new Date('2026-09-07'),endDate:new Date('2026-10-09'),examDate:new Date('2026-10-12'),priceCents:165000,priceLabel:'1 650 €',location:'Puget-sur-Argens / Côte d’Azur',status:'OPEN',seatsTotal:null,seatsLeft:8,showSeatsLeft:true,durationLabel:'175 heures',registrationUrl:'/formations-securite/aps',fundingNotes:'Financement possible selon votre situation : CPF, France Travail ou financement personnel à vérifier avec l’équipe.',publicNotes:'Formation de 5 semaines, soit 175 heures.',internalNotes:'',sortOrder:0,isHighlighted:true,createdAt:new Date(),updatedAt:new Date()}];

function norm(s:string){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
export function detectTrainingSlugs(q:string){const n=norm(q); const slugs:string[]=[]; if(/\baps\b|agent de securite|agent de prevention/.test(n)) slugs.push('aps'); if(/ssiap|incendie|securite incendie/.test(n)) slugs.push('ssiap-1'); if(/a3p|apr|protection rapprochee|garde du corps|bodyguard/.test(n)) slugs.push('a3p-apr'); if(/bts|\bmos\b|\bmco\b|ndrc|alternance/.test(n)) slugs.push('bts-mos','bts-mco'); if(/vtc|chauffeur vtc|carte vtc/.test(n)) slugs.push('vtc'); if(/desp|dssp|dirigeant/.test(n)) slugs.push('desp-dssp'); return [...new Set(slugs)];}
export async function listTrainings(){const p=await getPrisma(); return p? p.training.findMany({orderBy:[{category:'asc'},{name:'asc'}]}) : baseTrainings;}
export async function listSessions(){const p=await getPrisma(); return p? p.trainingSession.findMany({include:{training:true},orderBy:[{sortOrder:'asc'},{startDate:'asc'}]}) : baseSessions;}
export async function listLeads(){const p=await getPrisma(); return p? p.chatLead.findMany({orderBy:{createdAt:'desc'}}) : [];}
export async function dashboardStats(){const [t,s,l]=await Promise.all([listTrainings(),listSessions(),listLeads()]); return {activeTrainings:t.filter((x:any)=>x.isActive).length,openSessions:s.filter((x:any)=>x.status==='OPEN').length,leadCount:l.length,lastLead:l[0]||null};}
export async function getRelevantDynamicTrainingData(question:string){const slugs=detectTrainingSlugs(question); const sessions=(await listSessions()).filter((s:any)=>s.status!=='HIDDEN' && (!slugs.length || slugs.includes(s.training?.slug))).sort((a:any,b:any)=> (a.status==='OPEN'?-2:a.status==='COMING_SOON'?-1:0) - (b.status==='OPEN'?-2:b.status==='COMING_SOON'?-1:0) || +new Date(a.startDate)- +new Date(b.startDate)); const trainings=(await listTrainings()).filter((t:any)=>!slugs.length || slugs.includes(t.slug)); const context=sessions.map((s:any)=>`Formation: ${s.training?.name} (${s.training?.title})\nPage: ${s.training?.pageUrl}\nSession: ${s.title}\nDates: du ${new Date(s.startDate).toLocaleDateString('fr-FR')} au ${new Date(s.endDate).toLocaleDateString('fr-FR')}\nExamen: ${s.examDate?new Date(s.examDate).toLocaleDateString('fr-FR'):'non précisé'}\nTarif: ${s.priceLabel} (${s.priceCents} centimes)\nLieu: ${s.location}\nStatut: ${s.status}\nPlaces restantes: ${s.seatsLeft ?? 'non précisé'}\nInscription: ${s.registrationUrl}\nFinancement: ${s.fundingNotes||'à vérifier avec l’équipe'}\nNotes publiques: ${s.publicNotes}`).join('\n\n---\n\n'); return {trainings,sessions,context,selectedDynamicTrainings:trainings.map((t:any)=>t.slug),selectedSessions:sessions.map((s:any)=>s.id)};}
