'use client';
import { useState } from 'react';
const formatSentAt = (value?: string | Date | null) => value ? new Date(value).toLocaleDateString('fr-FR') : '';
function Badge({ sent }: { sent: boolean }) { return <span className={`rounded-full px-3 py-1 text-xs font-black ${sent ? 'bg-emerald-100 text-emerald-700' : 'bg-red-100 text-red-700'}`}>{sent ? 'Envoyé' : 'En attente'}</span>; }
export function ApsDocumentsCard({ trainee }: { trainee: any }) {
  const [row, setRow] = useState(trainee); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  async function send() { setLoading(true); setMessage(''); const response = await fetch(`/api/admin/trainees/${row.id}/convocation-aps`, { method: 'POST' }); const data = await response.json().catch(() => ({})); setLoading(false); if (!response.ok) { setMessage(data.error || 'Envoi impossible.'); return; } setRow(data); setMessage('Convocation envoyée avec succès.'); }
  const sent = row.convocationApsStatus === 'sent';
  return <section className="mt-6 rounded-[1.5rem] border border-stone-200 bg-white p-6 shadow-[0_18px_50px_rgba(15,23,42,.08)]"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-academy-gold/15 text-xl">📄</span><h2 className="text-2xl font-black text-academy-ink">Convocations et attestations</h2></div>{message ? <p className={`mt-4 rounded-xl border p-3 text-sm font-semibold ${message.includes('succès') ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'border-red-200 bg-red-50 text-red-800'}`}>{message}</p> : null}<div className="mt-5 divide-y divide-stone-100"><div className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="font-black">Convocation</p>{sent ? <p className="mt-1 text-sm text-stone-500">Convocation envoyée le {formatSentAt(row.convocationApsSentAt)}</p> : <p className="mt-1 text-sm text-stone-500">Prête à générer depuis le modèle APS.</p>}</div><div className="flex flex-wrap items-center gap-2"><Badge sent={sent}/>{sent ? <a target="_blank" className="rounded-xl border px-4 py-2 font-bold" href={`/api/admin/trainees/${row.id}/convocation-aps/pdf`}>Voir la convocation</a> : null}<button type="button" onClick={send} disabled={loading} className="rounded-xl bg-academy-ink px-4 py-2 font-bold text-white disabled:cursor-wait disabled:opacity-60">{loading ? 'Envoi en cours…' : sent ? 'Renvoyer' : 'Envoyer la convocation'}</button></div></div>{['Attestation entrée en formation','Attestation fin de formation'].map(label => <div key={label} className="flex flex-wrap items-center justify-between gap-3 py-4"><p className="font-black">{label}</p><div className="flex items-center gap-2"><Badge sent={false}/><button disabled className="rounded-xl border bg-stone-50 px-4 py-2 font-bold text-stone-400">Bientôt disponible</button></div></div>)}</div></section>;
}
