import { PublicTrainingSessions, isPublicUpcomingSession } from '@/components/PublicTrainingSessions';
import { Button, ConversionStrip, FeatureCard, PremiumFAQSection } from '@/components/ui';
import { DespHero } from '@/components/DespHero';
import { listSessions } from '@/lib/training-data';
import { formationFaq } from '@/data/faq';
import { despActivities, despEnrollmentSteps, despFinancingCards, despInitialAdminData, despInitialFaq, despOutcomes } from '@/data/despInitial';

export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'Formation DESP initial – Dirigeant de sécurité privée | Intégrale Academy',
  description: 'Préparez le titre RNCP niveau 5 de dirigeant d’entreprise de sécurité privée. Formation DESP de 245 heures à distance et en présentiel, éligible aux financements selon votre situation.',
};

const contactHref = '/contact?formation=desp-initial';

const jobMissions = ['Créer ou reprendre une entreprise','Piloter la stratégie et les finances','Garantir la conformité réglementaire','Recruter et manager les équipes','Développer l’activité commerciale','Répondre aux appels d’offres','Superviser les prestations','Gérer les relations avec les clients'];
const audience = ['créateurs d’entreprise','repreneurs d’une société de sécurité','responsables d’agence','responsables d’exploitation','managers de la sécurité privée','chefs d’équipe souhaitant évoluer','dirigeants souhaitant régulariser ou développer leur activité','personnes en reconversion disposant d’un projet sérieux de création ou de reprise'];
const prerequisites = ['être majeur','maîtriser le français à l’oral et à l’écrit','disposer d’un niveau baccalauréat ou équivalent','ou être titulaire du SSIAP 3','ou justifier d’une expérience sur un poste à responsabilités','ou obtenir un avis favorable à l’entretien préalable d’admission selon le profil'];
const cnaps = ['la condition de nationalité applicable','l’honorabilité','l’absence de condamnations incompatibles','l’absence d’interdiction de gérer ou de faillite personnelle incompatible','l’absence d’activité incompatible','l’aptitude professionnelle','la cohérence et la complétude du dossier'];
const project = ['choix des activités','étude du marché','modèle économique','organisation de l’entreprise','prévisionnel financier','politique commerciale','besoins en recrutement','obligations CNAPS','plan de développement'];
const evaluation = ['épreuve écrite sous forme de QCU','études de cas','mises en situation professionnelles','projet de création ou de reprise','évaluations portant sur la gestion financière et administrative','évaluations commerciales','évaluations de management','soutenances orales devant un jury professionnel'];
const outcomes = despOutcomes;
const why = ['Parcours structuré pour apprendre le métier étape par étape.','Modalités hybrides avec centres Paris, Côte d’Azur et Aurillac selon planning.','Accompagnement pédagogique et administratif jusqu’à l’examen.'];
const programAxes = [
  ['Axe 1 — Créer ou reprendre une entreprise',['analyser le marché','définir le positionnement','choisir les activités','construire le projet','réaliser un business plan','comparer les formes juridiques','prévoir les besoins financiers','effectuer les démarches de création ou de reprise']],
  ['Axe 2 — Sécuriser la conformité réglementaire',['Livre VI du Code de la sécurité intérieure','rôle et pouvoirs du CNAPS','agrément dirigeant','autorisation d’exercice de l’entreprise','cartes professionnelles des salariés','déontologie','sous-traitance','contrats de prestations','obligations de contrôle','règles propres aux différentes activités de sécurité privée']],
  ['Axe 3 — Piloter la gestion financière, juridique et administrative',['comptabilité','budget prévisionnel','trésorerie','rentabilité','coûts de revient','facturation','TVA et fiscalité','assurances','achats et équipements','maintenance','contrats de travail','obligations sociales']],
  ['Axe 4 — Développer l’activité commerciale',['étude de marché','stratégie marketing','communication','prospection','partenariats','construction d’une offre','calcul du prix de vente','veille sur les marchés','lecture d’un cahier des charges','réponse à un appel d’offres','négociation','suivi et fidélisation des clients']],
  ['Axe 5 — Recruter et manager les équipes',['organisation des recrutements','vérification des titres CNAPS','entretiens','intégration','planification','répartition des rôles','management opérationnel','objectifs','évaluation','gestion des conflits','discipline','formation','développement des compétences','évolution professionnelle']],
] as const;

async function getSessions(){return (await listSessions()).filter((session:any)=>isPublicUpcomingSession(session)&&['desp-initial','desp-dssp','desp'].includes(session.training?.slug));}

export default async function DespInitialPage(){
  const sessions = await getSessions();
  return <main className="relative overflow-hidden pb-28 lg:pb-0">
    <DespHero variant="initial" title="Formation DESP initial : devenez dirigeant d’entreprise de sécurité privée" subtitle={<><p>Apprenez étape par étape à créer, reprendre ou diriger une entreprise de sécurité privée avec un parcours DESP structuré, hybride et orienté projet professionnel.</p><p>Intégrale Academy vous accompagne sur la réglementation CNAPS, la gestion, le management, le développement commercial et la préparation aux évaluations du titre RNCP.</p></>} stats={[["Durée","245 h","175 h à distance + 70 h en présentiel"],["Rythme","7 semaines","parcours intensif"],["Tarif",despInitialAdminData.priceLabel,"selon offre administrée"],["Lieux","3 sites","Paris, Côte d’Azur ou Aurillac"],["RNCP",despInitialAdminData.rncpCode,"niveau 5"],["Objectif","CNAPS","préparer l’agrément dirigeant"]]} sessions={sessions}/>
    <section className="page-container py-10"><div className="grid gap-4 md:grid-cols-3"><FeatureCard title="Durée">7 semaines · 245 heures</FeatureCard><FeatureCard title="Public concerné">Candidats souhaitant acquérir ou consolider les compétences de dirigeant en sécurité privée.</FeatureCard><FeatureCard title="Prérequis">Niveau 4 ou expérience à valider avec l’équipe admissions ; conditions CNAPS et honorabilité à vérifier.</FeatureCard><FeatureCard title="Lieux">Distanciel + présentiel à Paris, Puget-sur-Argens ou Aurillac selon les sessions.</FeatureCard><FeatureCard title="Financement">CPF, France Travail, entreprise ou facilités de paiement selon dossier.</FeatureCard><FeatureCard title="Certification / examen"><strong>Titre RNCP Dirigeant d’entreprise de sécurité privée – niveau 5</strong><br/>Titre : Dirigeant d’entreprise de sécurité privée · Sigle : DESP · Code : {despInitialAdminData.rncpCode} · Certificateur : Scotia Formation · Échéance actuelle : 28 mars 2027 · Durée : {despInitialAdminData.duration.total} · Tarif actuel : {despInitialAdminData.priceLabel}<br/><span className="mt-2 block">Cette certification permet de justifier de l’aptitude professionnelle nécessaire à la demande d’agrément dirigeant auprès du CNAPS. L’agrément reste délivré séparément par le CNAPS après étude du dossier.</span></FeatureCard></div></section>
    <PublicTrainingSessions sessions={sessions} title="Prochaines dates DESP initial" intro="Dates, lieux, tarifs, places restantes, statuts, périodes à distance / présentiel et liens d’inscription proviennent directement de l’administration." displayLimit={0}/>
    <ConversionStrip/>
    <TextSection title="Quel est le rôle d’un dirigeant d’entreprise de sécurité privée ?" intro="Le dirigeant d’entreprise de sécurité privée crée, reprend, dirige ou développe une structure exerçant une ou plusieurs activités réglementées de sécurité privée. Il veille au respect du Livre VI du Code de la sécurité intérieure, pilote la stratégie de l’entreprise, contrôle son équilibre financier, développe son activité commerciale et encadre les équipes."><CardGrid items={jobMissions}/><Note>Le dirigeant ne réalise pas nécessairement lui-même les missions opérationnelles. S’il exerce personnellement des activités d’agent de sécurité, il doit également détenir la carte professionnelle correspondant à l’activité exercée.</Note></TextSection>
    <Info title="À qui s’adresse la formation ?" items={audience}/><NoteSection>La formation ne s’adresse pas uniquement aux agents de sécurité expérimentés. Une expérience du secteur constitue un avantage, mais l’admission dépend de l’ensemble du profil et des conditions du certificateur.</NoteSection>
    <TextSection title="Quels sont les prérequis pour entrer en DESP initial ?"><CardGrid items={prerequisites}/><Note>Chaque candidature est étudiée individuellement. Un entretien préalable permet de vérifier le niveau, l’expérience, la cohérence du projet et la capacité à suivre une formation intensive de niveau 5.</Note></TextSection>
    <TextSection title="Quelles conditions faut-il remplir pour obtenir l’agrément dirigeant ?" intro="Le CNAPS vérifie notamment :"><CardGrid items={cnaps}/><Note>La réussite au titre DESP ne garantit pas automatiquement la délivrance de l’agrément. La décision appartient au CNAPS après enquête administrative.</Note><div className="mt-5"><Button href={contactHref}>Faire vérifier mes prérequis</Button></div></TextSection>
    <TextSection title="Une formation hybride de 245 heures"><div className="grid gap-4 md:grid-cols-2"><ListCard title="5 semaines à distance – 175 heures" items={['plateforme pédagogique accessible en ligne','cours et ressources numériques','études de cas','travaux individuels','préparation du projet professionnel','accompagnement par l’équipe pédagogique','évaluations et suivi de progression']}/><ListCard title="2 semaines en présentiel – 70 heures" items={['mises en situation','études de cas collectives','entraînements aux évaluations','travail sur la création ou la reprise d’entreprise','gestion financière et commerciale','management','préparation aux soutenances et au jury']}/></div><p className="mt-5 text-sm font-semibold leading-6 text-academy-muted">Lieux possibles selon les sessions administrées : Paris, Puget-sur-Argens ou Aurillac.</p></TextSection>
    <ProgramSection/>
    <FinancingSection/>
    <EnrollmentSection/>
    <TextSection title="Construisez votre véritable projet d’entreprise" intro="La formation ne se limite pas à l’apprentissage de la réglementation. Le candidat travaille sur un projet concret de création, de reprise ou de développement d’une entreprise de sécurité privée."><CardGrid items={project}/><Note>Les travaux réalisés pendant la formation restent pédagogiques et ne remplacent pas les conseils personnalisés d’un avocat, d’un expert-comptable ou d’un professionnel du droit.</Note></TextSection>
    <TextSection title="Modalités d’évaluation"><CardGrid items={evaluation}/><Note>La certification est obtenue lorsque l’ensemble des évaluations obligatoires relatives aux cinq activités est validé. Le référentiel actuel prévoit neuf évaluations portant sur cinq activités. Les durées exactes d’examen ne sont affichées que lorsqu’elles sont confirmées par l’administration.</Note></TextSection>
    <TextSection title="À l’issue de la formation"><div className="grid gap-3 md:grid-cols-4">{['Valider les évaluations','Obtenir le titre RNCP40385 de niveau 5','Déposer la demande d’agrément dirigeant auprès du CNAPS','Demander l’autorisation d’exercice de l’entreprise créée ou reprise'].map((step,i)=><div key={step} className="rounded-2xl bg-academy-surface p-4 ring-1 ring-academy-line"><span className="grid h-9 w-9 place-items-center rounded-full bg-academy-gold font-black text-academy-gold-text">{i+1}</span><p className="mt-3 font-black text-academy-ink">{step}</p></div>)}</div><Note>Le titre, l’agrément personnel du dirigeant et l’autorisation d’exercice de l’entreprise sont trois éléments distincts. Si le dirigeant réalise lui-même des missions opérationnelles de sécurité, il doit également posséder la carte professionnelle correspondante.</Note></TextSection>
    <TextSection title="Combien de temps l’agrément dirigeant est-il valable ?" intro="L’agrément dirigeant est valable cinq ans. Son renouvellement doit être demandé auprès du CNAPS au moins trois mois avant son expiration."><Note>Ce renouvellement ne doit pas être confondu avec un MAC APS.</Note></TextSection>
    <Info title="Débouchés" items={outcomes}/><NoteSection>Le titre ne garantit ni la création effective d’une entreprise, ni la délivrance de l’agrément, ni la rentabilité du projet.</NoteSection>
    <ActivitiesSection/>
    <AccessibilitySection/>
    <Info title="Pourquoi suivre cette formation chez Intégrale Academy" items={why}/>
    <PremiumFAQSection badge="FAQ DESP initial" title="Vos questions sur la formation DESP initial" description="Retrouvez les réponses essentielles sur le déroulement du parcours, les prérequis, les financements, l’examen, le CNAPS et les étapes d’inscription." items={[...formationFaq, ...despInitialFaq]} contactHref="/contact?formation=desp-initial" contactLabel="Poser une question"/>
  </main>
}

function TextSection({title,intro,children}:{title:string;intro?:string;children?:React.ReactNode}){return <section className="page-container py-10 sm:py-14"><div className="mb-8 max-w-3xl"><p className="text-xs font-black uppercase tracking-[.24em] text-academy-gold">DESP initial</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">{title}</h2>{intro&&<p className="mt-4 text-lg leading-8 text-academy-muted">{intro}</p>}</div>{children}</section>}
function CardGrid({items}:{items:string[]}){return <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4">{items.map(i=><div key={i} className="reveal rounded-2xl border border-academy-line bg-academy-surface p-4 font-semibold text-academy-muted shadow-soft">✓ {i}</div>)}</div>}
function ListCard({title,items}:{title:string;items:string[]}){return <div className="rounded-2xl bg-academy-surface p-5 ring-1 ring-academy-line"><h3 className="text-xl font-black text-academy-ink">{title}</h3><ul className="mt-4 space-y-2 text-sm font-semibold leading-6 text-academy-muted">{items.map(i=><li key={i}>✓ {i}</li>)}</ul></div>}
function Note({children}:{children:React.ReactNode}){return <p className="mt-5 rounded-2xl border border-academy-gold/35 bg-academy-gold/10 p-4 font-bold leading-7 text-academy-ink">{children}</p>}
function NoteSection({children}:{children:React.ReactNode}){return <section className="page-container py-2"><Note>{children}</Note></section>}
function ProgramSection(){return <section className="page-container py-10 sm:py-14"><div className="mb-8 max-w-3xl"><p className="text-xs font-black uppercase tracking-[.24em] text-academy-gold">Programme</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Programme détaillé</h2></div><div className="space-y-3">{programAxes.map(([title,items],index)=><details key={title} open={index===0} className="group rounded-2xl border border-academy-line bg-academy-elevated p-5 shadow-soft"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-black"><span>{title}</span><span className="grid h-8 w-8 place-items-center rounded-full bg-academy-gold text-academy-gold-text transition group-open:rotate-45">+</span></summary><ul className="mt-4 grid gap-2 text-academy-muted sm:grid-cols-2">{items.map(item=><li key={item} className="flex gap-2 text-sm font-semibold leading-6"><span className="text-academy-gold">✓</span><span>{item}</span></li>)}</ul></details>)}</div></section>}
function Info({title,items}:{title:string;items:string[]}){return <section className="page-container py-10 sm:py-14"><div className="mb-8 max-w-3xl"><p className="text-xs font-black uppercase tracking-[.24em] text-academy-gold">Repères</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">{title}</h2></div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{items.map(i=><div key={i} className="rounded-2xl border border-academy-line bg-academy-surface p-4 shadow-soft"><p className="font-semibold leading-7 text-academy-muted">✓ {i}</p></div>)}</div></section>}

function FinancingSection(){return <TextSection title="Financements possibles" intro="Chaque solution est étudiée selon votre situation, l’offre active et les règles du financeur. Aucun financement n’est automatique."><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{despFinancingCards.map(([title,text])=><FeatureCard key={title} title={title}>{text}</FeatureCard>)}</div><div className="mt-6"><Button href="/contact?formation=desp-initial&objet=financement">Étudier le financement de mon DESP</Button></div></TextSection>}
function EnrollmentSection(){return <TextSection title="Étapes d’inscription"><div className="grid gap-3 md:grid-cols-5">{despEnrollmentSteps.map((step,i)=><div key={step} className="rounded-2xl bg-academy-surface p-4 ring-1 ring-academy-line"><span className="grid h-9 w-9 place-items-center rounded-full bg-academy-gold font-black text-academy-gold-text">{i+1}</span><p className="mt-3 font-black text-academy-ink">{step}</p></div>)}</div><div className="mt-6"><Button href="/contact?formation=desp-initial&objet=inscription">Commencer mon inscription</Button></div></TextSection>}
function ActivitiesSection(){return <TextSection title="Activités concernées" intro="Les entreprises de sécurité peuvent intervenir, selon leurs autorisations, dans différentes activités réglementées."><CardGrid items={despActivities}/><Note>Chaque activité est soumise à ses propres conditions, qualifications et autorisations. Le titre DESP ne permet pas automatiquement d’exercer toutes ces activités.</Note></TextSection>}
function AccessibilitySection(){const ref=despInitialAdminData.handicapReferent;return <TextSection title="Accessibilité"><p className="rounded-2xl bg-academy-surface p-5 font-semibold leading-7 text-academy-muted ring-1 ring-academy-line">Intégrale Academy étudie les besoins d’adaptation pédagogique et matérielle de chaque candidat. Contactez le référent handicap avant l’inscription afin d’identifier les aménagements compatibles avec le parcours et les évaluations.</p><div className="mt-5 rounded-2xl border border-academy-line bg-white p-5"><h3 className="font-black">Référent handicap</h3><p className="mt-2 text-academy-muted">{ref.name} · {ref.email} · {ref.phone}</p></div></TextSection>}
