import { Button, ChatGptAgentBanner, ConversionStrip, FAQ, FeatureCard, FinancingCard, FormationCard, FullWidthBand, Hero, LocationCard, ProofBar, SectionTitle, StatCard, VisualJourneyShowcase } from '@/components/ui';
import { OrientationAssistant } from '@/components/OrientationAssistant';
import { globalFaq } from '@/data/faq';
import { bts, contact, securityFormations, vtcFormation } from '@/data/site';

export const metadata={title:'Accueil',description:'Intégrale Academy forme aux métiers de la sécurité privée, sécurité incendie, VTC et BTS en alternance à Puget-sur-Argens, Paris et Aurillac.'};

export default function Home(){
  const securityHighlights=securityFormations.slice(0,6);
  const btsHighlights=bts.slice(0,6).map(x=>({title:x.title,short:x.desc,slug:x.slug,tags:x.tags}));
  return <>
    <Hero badge="Centre de formation agréé" title="Formez-vous aux métiers de la sécurité, du commerce et du transport avec Intégrale Academy" subtitle="Centre de formation professionnelle spécialisé dans la sécurité privée, la sécurité incendie, le VTC et les BTS en alternance." actions={<><Button href="/formations-securite">Voir les formations</Button><Button href="/contact" variant="secondary">Être rappelé</Button><Button href="/contact" variant="ghost">Demander des informations</Button></>} visual={<OrientationAssistant/>}/>
    <ProofBar/>
    <ConversionStrip/>
    <ChatGptAgentBanner/>
    <VisualJourneyShowcase/>
    <FullWidthBand eyebrow="Parcours lisible" title="Trois familles de parcours, sans les mélanger" actions={<><Button href="/planning" variant="secondary">Voir le planning</Button><Button href="/tarifs" variant="ghost">Consulter les tarifs</Button></>}>Les formations professionnelles sécurité privée, la formation chauffeur VTC et les BTS en alternance répondent à des objectifs différents. La page d’accueil les présente donc séparément pour vous orienter plus vite.</FullWidthBand>
    <section className="mx-auto max-w-7xl px-4 py-12">
      <SectionTitle eyebrow="3 parcours distincts" title="Choisissez d’abord votre famille de formation">Chaque bloc correspond à une demande différente : métier de la sécurité privée, chauffeur VTC ou diplôme BTS en alternance.</SectionTitle>
      <div className="grid gap-5 lg:grid-cols-3">
        <FormationCard title="1. Formations professionnelles métiers de la sécurité privée" desc="APS, SSIAP, A3P/APR, DESP ou CPSP : des parcours certifiants pour exercer, évoluer ou encadrer dans la sécurité privée et la sécurité incendie." href="/formations-securite" tags={['Sécurité privée','Certifications métier']}/>
        <FormationCard title="2. Formation Chauffeur VTC" desc={vtcFormation.short} href={vtcFormation.slug} tags={['VTC','Transport de personnes']}/>
        <FormationCard title="3. BTS en alternance" desc="Des diplômes d’État en alternance, séparés des formations professionnelles courtes : MOS, MCO, NDRC, Commerce International, Immobilier et Comptabilité-Gestion." href="/bts" tags={['Alternance','Diplômes d’État']}/>
      </div>
    </section>
    <section className="mx-auto max-w-7xl px-4 py-12"><SectionTitle eyebrow="1. Sécurité privée" title="Formations professionnelles aux métiers de la sécurité">Ces formations visent l’accès ou l’évolution dans les métiers de la sécurité privée, de la protection rapprochée, du management sécurité ou de la sécurité incendie.</SectionTitle><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{securityHighlights.map(f=><FormationCard key={f.slug} title={f.title} desc={f.short} href={f.slug} tags={['Sécurité privée',f.duration]}/>)}</div></section>
    <section className="mx-auto max-w-7xl px-4 py-12"><SectionTitle eyebrow="2. Chauffeur VTC" title="Une formation dédiée au transport de personnes">Le parcours VTC est présenté à part : il ne relève ni des métiers de la sécurité privée, ni des BTS en alternance.</SectionTitle><div className="mx-auto max-w-3xl"><FormationCard title={vtcFormation.title} desc={vtcFormation.short} href={vtcFormation.slug} tags={[vtcFormation.duration,'VTC','CPF selon éligibilité']}/></div></section>
    <section className="mx-auto max-w-7xl px-4 py-12"><SectionTitle eyebrow="3. BTS en alternance" title="Diplômes BTS : un parcours long en entreprise et en centre">Les BTS sont des diplômes d’État en alternance. Ils sont volontairement séparés des formations professionnelles métiers de la sécurité privée et du VTC.</SectionTitle><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{btsHighlights.map(f=><FormationCard key={f.slug} title={f.title} desc={f.short} href={f.slug} tags={f.tags}/>)}</div></section>
    <section className="mx-auto max-w-7xl px-4 py-12"><SectionTitle eyebrow="Pourquoi nous choisir" title="Un organisme rassurant pour candidats, financeurs et entreprises"/><div className="grid gap-5 md:grid-cols-3"><FeatureCard title="Agréments et certifications">Qualiopi, CNAPS, ADEF, SSIAP, INRS SST, UAI et références réglementaires affichées pour faciliter les démarches.</FeatureCard><FeatureCard title="Accompagnement candidat">Aide au choix de formation, financement, devis, rappel et préparation à l’inscription.</FeatureCard><FeatureCard title="Approche professionnelle">Pages longues restructurées, informations utiles visibles, CTA clairs et parcours sans friction.</FeatureCard></div></section>
    <FullWidthBand eyebrow="Accompagnement" title="Des conseillers vous aident à valider le bon financement" tone="gold" actions={<><Button href="/financements" variant="ghost">Explorer les financements</Button><Button href="/contact">Être accompagné</Button></>}>CPF, France Travail, alternance ou OPCO : nous vous orientons selon votre situation avant l’inscription, le devis ou la constitution du dossier.</FullWidthBand>
    <section className="mx-auto max-w-7xl px-4 py-12"><SectionTitle eyebrow="Nos centres" title="Paris, Côte d’Azur et Centre France"/><div className="grid gap-5 md:grid-cols-3">{contact.locations.map(l=><LocationCard key={l.name} {...l}/>)}</div></section>
    <section className="mx-auto max-w-7xl px-4 py-12"><SectionTitle eyebrow="Financements" title="Des solutions selon votre situation"/><div className="grid gap-5 md:grid-cols-4"><FinancingCard title="CPF" href="/financements/cpf">Mobilisable selon éligibilité de la formation.</FinancingCard><FinancingCard title="France Travail" href="/financements/france-travail">Accompagnement possible selon dossier.</FinancingCard><FinancingCard title="Alternance" href="/financements/alternance">BTS gratuits pour apprentis selon prise en charge.</FinancingCard><FinancingCard title="Entreprise / OPCO" href="/entreprises">Former salariés ou recruter un alternant.</FinancingCard></div></section>
    <section className="mx-auto max-w-7xl px-4 py-12"><div className="grid gap-4 md:grid-cols-4"><StatCard value="400 m²" label="Dédiés aux enseignements pratiques et théoriques"/><StatCard value="3" label="Implantations disponibles"/><StatCard value="10" label="Parcours formation et BTS présentés"/><StatCard value="08h-19h" label="Standard du lundi au vendredi"/></div></section>
    <FullWidthBand eyebrow="Inscription" title="Une prochaine session peut correspondre à votre projet" tone="light" actions={<><Button href="/contact">Demander des informations</Button><Button href="tel:0422470768" variant="secondary">Appeler</Button></>}>Indiquez votre formation cible, votre ville et votre mode de financement : l’équipe revient vers vous avec les informations utiles.</FullWidthBand>
    <section className="px-4 py-12"><SectionTitle eyebrow="FAQ" title="Questions fréquentes"/><FAQ items={globalFaq}/></section>
  </>
}
