import { Button, ChatGptAgentBanner, ContactBlock, ConversionStrip, FAQ, FeatureCard, FinancingCard, FormationCard, FullWidthBand, Hero, LocationCard, ProofBar, SectionTitle, StatCard, VisualJourneyShowcase } from '@/components/ui';
import { globalFaq } from '@/data/faq';
import { bts, contact, formations } from '@/data/site';

export const metadata={title:'Accueil',description:'Intégrale Academy forme aux métiers de la sécurité privée, sécurité incendie, VTC et BTS en alternance à Puget-sur-Argens, Paris et Aurillac.'};

export default function Home(){
  const main=[...formations.filter(f=>f.category!=='bts').slice(0,6), ...bts.slice(0,3).map(x=>({title:x.title,short:x.desc,slug:x.slug}))];
  return <>
    <Hero badge="Centre de formation agréé" title="Formez-vous aux métiers de la sécurité, du commerce et du transport avec Intégrale Academy" subtitle="Centre de formation professionnelle spécialisé dans la sécurité privée, la sécurité incendie, le VTC et les BTS en alternance." actions={<><Button href="/formations-securite">Voir les formations</Button><Button href="/contact" variant="secondary">Être rappelé</Button><Button href="/contact" variant="ghost">Demander des informations</Button></>}/>
    <ProofBar/>
    <ConversionStrip/>
    <ChatGptAgentBanner/>
    <VisualJourneyShowcase/>
    <FullWidthBand eyebrow="Parcours lisible" title="Un site plus rythmé pour aller vite à l’essentiel" actions={<><Button href="/planning" variant="secondary">Voir le planning</Button><Button href="/tarifs" variant="ghost">Consulter les tarifs</Button></>}>Sécurité, VTC ou BTS : les informations clés sont regroupées par temps forts visuels, avec des bandeaux pleine largeur pour mieux repérer les étapes importantes.</FullWidthBand>
    <section className="mx-auto max-w-7xl px-4 py-12"><SectionTitle eyebrow="Formations principales" title="Des parcours clairs, certifiants et orientés métier">Sécurité, VTC et BTS en alternance, avec des informations utiles pour choisir, financer et préparer son inscription.</SectionTitle><div className="grid gap-5 md:grid-cols-3">{main.map(f=><FormationCard key={f.slug} title={f.title} desc={f.short} href={f.slug} tags={['Lieu','Financement possible']}/>)}</div></section>
    <section className="mx-auto max-w-7xl px-4 py-12"><SectionTitle eyebrow="Pourquoi nous choisir" title="Un organisme rassurant pour candidats, financeurs et entreprises"/><div className="grid gap-5 md:grid-cols-3"><FeatureCard title="Agréments et certifications">Qualiopi, CNAPS, ADEF, SSIAP, INRS SST, UAI et références réglementaires affichées pour faciliter les démarches.</FeatureCard><FeatureCard title="Accompagnement candidat">Aide au choix de formation, financement, devis, rappel et préparation à l’inscription.</FeatureCard><FeatureCard title="Approche professionnelle">Pages longues restructurées, informations utiles visibles, CTA clairs et parcours sans friction.</FeatureCard></div></section>
    <FullWidthBand eyebrow="Accompagnement" title="Des conseillers vous aident à valider le bon financement" tone="gold" actions={<><Button href="/financements" variant="ghost">Explorer les financements</Button><Button href="/contact">Être accompagné</Button></>}>CPF, France Travail, alternance ou OPCO : nous vous orientons selon votre situation avant l’inscription, le devis ou la constitution du dossier.</FullWidthBand>
    <section className="mx-auto max-w-7xl px-4 py-12"><SectionTitle eyebrow="Nos centres" title="Paris, Côte d’Azur et Centre France"/><div className="grid gap-5 md:grid-cols-3">{contact.locations.map(l=><LocationCard key={l.name} {...l}/>)}</div></section>
    <section className="mx-auto max-w-7xl px-4 py-12"><SectionTitle eyebrow="Financements" title="Des solutions selon votre situation"/><div className="grid gap-5 md:grid-cols-4"><FinancingCard title="CPF" href="/financements/cpf">Mobilisable selon éligibilité de la formation.</FinancingCard><FinancingCard title="France Travail" href="/financements/france-travail">Accompagnement possible selon dossier.</FinancingCard><FinancingCard title="Alternance" href="/financements/alternance">BTS gratuits pour apprentis selon prise en charge.</FinancingCard><FinancingCard title="Entreprise / OPCO" href="/entreprises">Former salariés ou recruter un alternant.</FinancingCard></div></section>
    <section className="mx-auto max-w-7xl px-4 py-12"><div className="grid gap-4 md:grid-cols-4"><StatCard value="400 m²" label="Dédiés aux enseignements pratiques et théoriques"/><StatCard value="3" label="Implantations disponibles"/><StatCard value="10" label="Parcours formation et BTS présentés"/><StatCard value="08h-19h" label="Standard du lundi au vendredi"/></div></section>
    <FullWidthBand eyebrow="Inscription" title="Une prochaine session peut correspondre à votre projet" tone="light" actions={<><Button href="/contact">Demander des informations</Button><Button href="tel:0422470768" variant="secondary">Appeler</Button></>}>Indiquez votre formation cible, votre ville et votre mode de financement : l’équipe revient vers vous avec les informations utiles.</FullWidthBand>
    <section className="px-4 py-12"><SectionTitle eyebrow="FAQ" title="Questions fréquentes"/><FAQ items={globalFaq}/></section>
  </>
}
