import Link from 'next/link';
import { contact, legalRefs } from '@/data/site';

export function Badge({children,tone='gold'}:{children:React.ReactNode;tone?:'gold'|'green'|'neutral'}){const c=tone==='green'?'bg-academy-green/10 text-green-700':tone==='gold'?'bg-academy-gold/25 text-stone-900':'bg-white text-stone-700 border border-academy-line';return <span className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ${c}`}>{children}</span>}
export function Button({href,children,variant='primary'}:{href:string;children:React.ReactNode;variant?:'primary'|'secondary'|'ghost'}){const c=variant==='primary'?'bg-academy-ink text-white hover:bg-black':variant==='secondary'?'bg-academy-gold text-academy-ink hover:brightness-95':'bg-white text-academy-ink ring-1 ring-academy-line hover:bg-stone-50';return <Link className={`inline-flex items-center justify-center rounded-full px-5 py-3 text-sm font-bold transition hover:-translate-y-0.5 ${c}`} href={href}>{children}</Link>}
export function SectionTitle({eyebrow,title,children}:{eyebrow?:string;title:string;children?:React.ReactNode}){return <div className="mx-auto mb-10 max-w-3xl text-center reveal">{eyebrow&&<Badge>{eyebrow}</Badge>}<h2 className="mt-4 text-3xl font-black tracking-tight md:text-5xl">{title}</h2>{children&&<p className="mt-4 text-lg text-stone-600">{children}</p>}</div>}
export function Hero({badge,title,subtitle,actions}:{badge?:string;title:string;subtitle:string;actions?:React.ReactNode}){return <section className="grid-soft gold-glow overflow-hidden px-4 py-16 md:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div className="reveal">{badge&&<Badge>{badge}</Badge>}<h1 className="mt-5 text-4xl font-black tracking-tight md:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-stone-600">{subtitle}</p>{actions&&<div className="mt-8 flex flex-wrap gap-3">{actions}</div>}</div><div className="relative rounded-[2rem] bg-white/90 p-6 shadow-soft ring-1 ring-academy-line backdrop-blur reveal"><div className="rounded-[1.5rem] bg-academy-bg p-6"><p className="text-sm font-bold text-stone-500">Centres & modalités</p><div className="mt-5 grid gap-3">{contact.locations.map(l=><div key={l.name} className="rounded-2xl bg-white p-4"><b>{l.name}</b><p className="text-sm text-stone-600">{l.address}</p></div>)}</div></div></div></div></section>}
const appointmentFormUrl = 'https://assistance-alw9.onrender.com/demande-informations-formations';

function AppointmentButton(){
  return <Link className="group inline-flex items-center justify-center gap-2 rounded-full bg-gradient-to-r from-academy-gold via-yellow-300 to-academy-gold px-5 py-3 text-sm font-black text-academy-ink shadow-gold ring-1 ring-yellow-300/70 transition hover:-translate-y-0.5 hover:brightness-105 focus:outline-none focus:ring-2 focus:ring-yellow-500 focus:ring-offset-2" href={appointmentFormUrl}><span>Prendre RDV</span><span className="transition group-hover:translate-x-0.5" aria-hidden="true">→</span></Link>
}

export function Header(){
  const nav=[['Accueil','/'],['Formations sécurité','/formations-securite'],['BTS','/bts'],['VTC','/vtc'],['Financements','/financements'],['Entreprises','/entreprises'],['Planning','/planning'],['Contact','/contact']];
  return <header className="sticky top-0 z-50 border-b border-academy-line/80 bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-4"><Link href="/" className="flex items-center gap-2 text-lg font-black"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-academy-gold text-academy-ink shadow-gold" aria-hidden="true">IA</span><span>Intégrale<span className="text-yellow-700"> Academy</span></span></Link><nav className="hidden gap-5 text-sm font-semibold lg:flex" aria-label="Navigation principale">{nav.map(([n,h])=><Link key={h} href={h} className="rounded-full px-2 py-1 text-stone-700 transition hover:bg-academy-gold/20 hover:text-academy-ink">{n}</Link>)}</nav><div className="hidden gap-2 sm:flex"><Button href="tel:0422470768" variant="ghost">Appeler</Button><Button href="/contact">Demander des informations</Button><AppointmentButton/></div><details className="relative lg:hidden"><summary className="list-none rounded-full border border-academy-line bg-white px-4 py-2 text-sm font-bold cursor-pointer">Menu</summary><div className="absolute right-0 mt-3 w-72 rounded-3xl bg-white p-4 shadow-soft ring-1 ring-academy-line"><nav className="grid gap-2" aria-label="Navigation mobile">{nav.map(([n,h])=><Link key={h} href={h} className="rounded-2xl px-4 py-3 font-semibold hover:bg-academy-bg">{n}</Link>)}</nav><div className="mt-3 grid gap-2"><Button href="tel:0422470768" variant="ghost">Appeler</Button><Button href="/contact">Demander des informations</Button><AppointmentButton/></div></div></details></div></header>
}
export function Footer(){return <footer className="mt-20 border-t border-academy-line bg-white px-4 py-12"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-4"><div><div className="text-xl font-black">Intégrale Academy</div><p className="mt-3 text-sm text-stone-600">Centre de formation professionnelle spécialisé sécurité privée, sécurité incendie, VTC et BTS en alternance.</p></div><div><b>Formations</b><ul className="mt-3 space-y-2 text-sm"><li><Link href="/formations-securite/aps">APS</Link></li><li><Link href="/formations-securite/ssiap-1">SSIAP 1</Link></li><li><Link href="/formations-securite/a3p-apr">A3P / APR</Link></li><li><Link href="/bts">BTS</Link></li></ul></div><div><b>Financements</b><ul className="mt-3 space-y-2 text-sm"><li><Link href="/financements/cpf">CPF</Link></li><li><Link href="/financements/france-travail">France Travail</Link></li><li><Link href="/financements/alternance">Alternance</Link></li><li><Link href="/mentions-legales">Mentions légales</Link></li><li><Link href="/politique-confidentialite">Politique de confidentialité</Link></li></ul></div><div><b>Coordonnées</b><p className="mt-3 text-sm text-stone-600">{contact.phone}<br/>{contact.hours}<br/>{contact.locations[0].address}</p></div></div><div className="mx-auto mt-8 max-w-7xl border-t border-academy-line pt-6 text-xs text-stone-500">{legalRefs.join(' · ')}</div></footer>}
export function Card({children}:{children:React.ReactNode}){return <div className="rounded-3xl bg-white p-6 shadow-soft ring-1 ring-academy-line reveal">{children}</div>}
export function FormationCard({title,desc,href,tags=[]}:{title:string;desc:string;href:string;tags?:string[]}){return <Card><div className="flex flex-wrap gap-2">{tags.map(t=><Badge key={t} tone="neutral">{t}</Badge>)}</div><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-stone-600">{desc}</p><div className="mt-6 flex flex-wrap gap-2"><Button href={href}>Découvrir</Button><Button href="/contact" variant="ghost">Demander des informations</Button></div></Card>}
export function FeatureCard({title,children}:{title:string;children:React.ReactNode}){return <Card><h3 className="text-lg font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-stone-600">{children}</p></Card>}
export function StatCard({value,label}:{value:string;label:string}){return <div className="rounded-3xl bg-academy-ink p-6 text-white"><div className="text-3xl font-black text-academy-gold">{value}</div><p className="mt-2 text-sm text-stone-200">{label}</p></div>}
export function FAQ({items}:{items:{q:string;a:string}[]}){return <div className="mx-auto max-w-3xl space-y-3">{items.map(i=><details key={i.q} className="rounded-2xl bg-white p-5 ring-1 ring-academy-line"><summary className="cursor-pointer font-bold">{i.q}</summary><p className="mt-3 text-sm text-stone-600">{i.a}</p></details>)}</div>}
export function ContactBlock(){return <section className="mx-auto max-w-7xl rounded-[2rem] bg-academy-ink p-8 text-white md:p-12"><h2 className="text-3xl font-black">Besoin d’un conseil formation ?</h2><p className="mt-3 text-stone-200">Un conseiller vous aide à choisir la bonne formation et le bon financement.</p><div className="mt-6 flex flex-wrap gap-3"><Button href="tel:0422470768" variant="secondary">Appeler</Button><Button href="/contact" variant="ghost">Être rappelé</Button></div></section>}
export function LocationCard({name,address,detail}:{name:string;address:string;detail:string}){return <FeatureCard title={name}>{address}<br/>{detail}</FeatureCard>}
export function FinancingCard({title,children,href}:{title:string;children:React.ReactNode;href:string}){return <FeatureCard title={title}>{children}<br/><Link className="mt-4 inline-block font-bold text-yellow-700" href={href}>En savoir plus →</Link></FeatureCard>}
export function CTASection(){return <ContactBlock/>}
export function ProofBar(){const items=['Qualiopi','CNAPS','ADEF','SSIAP','INRS SST','UAI'];return <section className="border-y border-academy-line bg-white/70 px-4 py-4"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-3 text-xs font-black uppercase tracking-[.18em] text-stone-500">{items.map(item=><span key={item} className="rounded-full bg-academy-bg px-4 py-2">{item}</span>)}</div></section>}
export function ConversionStrip(){return <section className="mx-auto max-w-7xl px-4 py-8"><div className="grid gap-4 rounded-[2rem] bg-white p-5 shadow-soft ring-1 ring-academy-line md:grid-cols-3"><div><b className="text-academy-ink">Un doute sur la bonne formation ?</b><p className="mt-1 text-sm text-stone-600">Un conseiller vérifie avec vous les prérequis, lieux, dates et financements.</p></div><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-academy-green/10 font-black text-green-700">✓</span><p className="text-sm font-semibold text-stone-700">Réponse orientée inscription, sans engagement.</p></div><div className="flex flex-wrap items-center justify-start gap-2 md:justify-end"><Button href="/contact">Demander des informations</Button><Button href="tel:0422470768" variant="secondary">Être rappelé</Button></div></div></section>}
export function StickyMobileCTA(){return <div className="fixed inset-x-0 bottom-0 z-40 border-t border-academy-line bg-white/95 p-3 shadow-soft backdrop-blur md:hidden"><div className="mx-auto grid max-w-md grid-cols-2 gap-2"><Button href="tel:0422470768" variant="ghost">Appeler</Button><Button href="/contact">Infos</Button></div></div>}
