import Link from 'next/link';
import { contact, legalRefs } from '@/data/site';

export function Badge({children,tone='gold'}:{children:React.ReactNode;tone?:'gold'|'green'|'neutral'}){const c=tone==='green'?'bg-academy-green/10 text-green-700':tone==='gold'?'bg-academy-gold/25 text-stone-900':'bg-white text-stone-700 border border-academy-line';return <span className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ${c}`}>{children}</span>}
export function Button({href,children,variant='primary'}:{href:string;children:React.ReactNode;variant?:'primary'|'secondary'|'ghost'}){const c=variant==='primary'?'bg-academy-ink text-white hover:bg-black':variant==='secondary'?'bg-academy-gold text-academy-ink hover:brightness-95':'bg-white text-academy-ink ring-1 ring-academy-line hover:bg-stone-50';return <Link className={`inline-flex items-center justify-center rounded-full px-5 py-3 text-sm font-bold transition ${c}`} href={href}>{children}</Link>}
export function SectionTitle({eyebrow,title,children}:{eyebrow?:string;title:string;children?:React.ReactNode}){return <div className="mx-auto mb-10 max-w-3xl text-center reveal">{eyebrow&&<Badge>{eyebrow}</Badge>}<h2 className="mt-4 text-3xl font-black tracking-tight md:text-5xl">{title}</h2>{children&&<p className="mt-4 text-lg text-stone-600">{children}</p>}</div>}
export function Hero({badge,title,subtitle,actions}:{badge?:string;title:string;subtitle:string;actions?:React.ReactNode}){return <section className="overflow-hidden px-4 py-16 md:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div className="reveal">{badge&&<Badge>{badge}</Badge>}<h1 className="mt-5 text-4xl font-black tracking-tight md:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-stone-600">{subtitle}</p>{actions&&<div className="mt-8 flex flex-wrap gap-3">{actions}</div>}</div><div className="relative rounded-[2rem] bg-white p-6 shadow-soft ring-1 ring-academy-line reveal"><div className="rounded-[1.5rem] bg-academy-bg p-6"><p className="text-sm font-bold text-stone-500">Centres & modalités</p><div className="mt-5 grid gap-3">{contact.locations.map(l=><div key={l.name} className="rounded-2xl bg-white p-4"><b>{l.name}</b><p className="text-sm text-stone-600">{l.address}</p></div>)}</div></div></div></div></section>}
export function Header(){const nav=[['Accueil','/'],['Formations sécurité','/formations-securite'],['BTS','/bts'],['VTC','/vtc'],['Financements','/financements'],['Entreprises','/entreprises'],['Planning','/planning'],['Contact','/contact']];return <header className="sticky top-0 z-50 border-b border-academy-line/80 bg-academy-bg/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-4"><Link href="/" className="text-lg font-black">Intégrale<span className="text-yellow-600"> Academy</span></Link><nav className="hidden gap-5 text-sm font-semibold lg:flex">{nav.map(([n,h])=><Link key={h} href={h} className="hover:text-yellow-700">{n}</Link>)}</nav><div className="flex gap-2"><Button href="tel:0422470768" variant="ghost">Appeler</Button><Button href="/contact">Demander des informations</Button></div></div></header>}
export function Footer(){return <footer className="mt-20 border-t border-academy-line bg-white px-4 py-12"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-4"><div><div className="text-xl font-black">Intégrale Academy</div><p className="mt-3 text-sm text-stone-600">Centre de formation professionnelle spécialisé sécurité privée, sécurité incendie, VTC et BTS en alternance.</p></div><div><b>Formations</b><ul className="mt-3 space-y-2 text-sm"><li><Link href="/formations-securite/aps">APS</Link></li><li><Link href="/formations-securite/ssiap-1">SSIAP 1</Link></li><li><Link href="/formations-securite/a3p-apr">A3P / APR</Link></li><li><Link href="/bts">BTS</Link></li></ul></div><div><b>Financements</b><ul className="mt-3 space-y-2 text-sm"><li><Link href="/financements/cpf">CPF</Link></li><li><Link href="/financements/france-travail">France Travail</Link></li><li><Link href="/financements/alternance">Alternance</Link></li><li><Link href="/mentions-legales">Mentions légales</Link></li><li><Link href="/politique-confidentialite">Politique de confidentialité</Link></li></ul></div><div><b>Coordonnées</b><p className="mt-3 text-sm text-stone-600">{contact.phone}<br/>{contact.hours}<br/>{contact.locations[0].address}</p></div></div><div className="mx-auto mt-8 max-w-7xl border-t border-academy-line pt-6 text-xs text-stone-500">{legalRefs.join(' · ')}</div></footer>}
export function Card({children}:{children:React.ReactNode}){return <div className="rounded-3xl bg-white p-6 shadow-soft ring-1 ring-academy-line reveal">{children}</div>}
export function FormationCard({title,desc,href,tags=[]}:{title:string;desc:string;href:string;tags?:string[]}){return <Card><div className="flex flex-wrap gap-2">{tags.map(t=><Badge key={t} tone="neutral">{t}</Badge>)}</div><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-stone-600">{desc}</p><div className="mt-6 flex flex-wrap gap-2"><Button href={href}>Découvrir</Button><Button href="/contact" variant="ghost">Demander des informations</Button></div></Card>}
export function FeatureCard({title,children}:{title:string;children:React.ReactNode}){return <Card><h3 className="text-lg font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-stone-600">{children}</p></Card>}
export function StatCard({value,label}:{value:string;label:string}){return <div className="rounded-3xl bg-academy-ink p-6 text-white"><div className="text-3xl font-black text-academy-gold">{value}</div><p className="mt-2 text-sm text-stone-200">{label}</p></div>}
export function FAQ({items}:{items:{q:string;a:string}[]}){return <div className="mx-auto max-w-3xl space-y-3">{items.map(i=><details key={i.q} className="rounded-2xl bg-white p-5 ring-1 ring-academy-line"><summary className="cursor-pointer font-bold">{i.q}</summary><p className="mt-3 text-sm text-stone-600">{i.a}</p></details>)}</div>}
export function ContactBlock(){return <section className="mx-auto max-w-7xl rounded-[2rem] bg-academy-ink p-8 text-white md:p-12"><h2 className="text-3xl font-black">Besoin d’un conseil formation ?</h2><p className="mt-3 text-stone-200">Un conseiller vous aide à choisir la bonne formation et le bon financement.</p><div className="mt-6 flex flex-wrap gap-3"><Button href="tel:0422470768" variant="secondary">Appeler</Button><Button href="/contact" variant="ghost">Être rappelé</Button></div></section>}
export function LocationCard({name,address,detail}:{name:string;address:string;detail:string}){return <FeatureCard title={name}>{address}<br/>{detail}</FeatureCard>}
export function FinancingCard({title,children,href}:{title:string;children:React.ReactNode;href:string}){return <FeatureCard title={title}>{children}<br/><Link className="mt-4 inline-block font-bold text-yellow-700" href={href}>En savoir plus →</Link></FeatureCard>}
export function CTASection(){return <ContactBlock/>}
export function ContactForm({type='candidat'}:{type?:string}){return <form className="grid gap-4 rounded-3xl bg-white p-6 shadow-soft ring-1 ring-academy-line"><input className="rounded-2xl border border-academy-line px-4 py-3" placeholder="Nom et prénom"/><input className="rounded-2xl border border-academy-line px-4 py-3" placeholder="Téléphone"/><input className="rounded-2xl border border-academy-line px-4 py-3" placeholder="Email"/><textarea className="min-h-32 rounded-2xl border border-academy-line px-4 py-3" placeholder={`Votre demande ${type}`}/><button className="rounded-full bg-academy-ink px-5 py-3 font-bold text-white" type="button">Envoyer la demande</button><p className="text-xs text-stone-500">Formulaire statique à connecter au service définitif.</p></form>}
