import { notFound } from 'next/navigation';
import { bts } from '@/data/site';
import { Button, FAQ, FeatureCard, Hero, SectionTitle } from '@/components/ui';

export function generateStaticParams(){return bts.map(x=>({slug:x.slug.split('/').pop()!}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const f=bts.find(x=>x.slug.endsWith(slug));return {title:f?.title||'BTS',description:f?.desc}}

function ListSection({title,items}:{title:string;items:string[]}){return <section className="mx-auto max-w-5xl px-4 py-8"><h2 className="text-2xl font-black">{title}</h2><div className="mt-5 grid gap-3">{items.map(i=><div key={i} className="rounded-2xl bg-white p-4 leading-7 text-stone-700 ring-1 ring-academy-line">{i}</div>)}</div></section>}

export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const f=bts.find(x=>x.slug.endsWith(slug));if(!f)notFound();return <><Hero badge="BTS en alternance" title={f.title} subtitle={f.desc} actions={<><Button href="/contact">Candidature</Button><Button href="/financements/alternance" variant="secondary">Financement alternance</Button><Button href="/contact" variant="ghost">Demande d’informations</Button></>}/><section className="mx-auto max-w-7xl px-4 py-10"><div className="grid gap-4 md:grid-cols-3"><FeatureCard title="Durée">{f.duration}</FeatureCard><FeatureCard title="Public concerné">{f.audience}</FeatureCard><FeatureCard title="Prérequis">{f.prerequisites}</FeatureCard><FeatureCard title="Lieu">{f.locations}</FeatureCard><FeatureCard title="Financement">{f.financing}</FeatureCard><FeatureCard title="Certification">{f.certification}</FeatureCard></div></section><ListSection title="Présentation" items={[f.desc]}/><ListSection title="Objectifs" items={f.objectives}/><ListSection title="Programme détaillé" items={f.program}/><ListSection title="Missions en entreprise" items={f.missions}/><ListSection title="Modalités d’évaluation" items={f.evaluation}/><ListSection title="Débouchés" items={f.outcomes}/><ListSection title="Qualités attendues" items={f.qualities}/><section className="px-4 py-10"><SectionTitle title="FAQ"/><FAQ items={f.faq}/></section></>}
