import { notFound } from 'next/navigation';
import { bts } from '@/data/site';
import { Button, FAQ, FeatureCard, Hero, SectionTitle } from '@/components/ui';
import { BtsAlternanceVisual, ExamVisual, ProgramModulesVisual, TrainingPathVisual, VisualSection } from '@/components/visuals';

export function generateStaticParams(){return bts.map(x=>({slug:x.slug.split('/').pop()!}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const f=bts.find(x=>x.slug.endsWith(slug));return {title:f?.title||'BTS',description:f?.desc}}

function ListSection({title,items}:{title:string;items:string[]}){const visual=title.includes('Programme')?<ProgramModulesVisual/>:title.includes('évaluation')?<ExamVisual/>:<BtsAlternanceVisual/>;return <VisualSection tone={title.includes('Programme')?'program':title.includes('évaluation')?'exam':'bts'}><section className="mx-auto max-w-6xl px-4 py-8"><div className="grid gap-6 lg:grid-cols-[.78fr_1.22fr] lg:items-start"><div>{visual}</div><div><h2 className="text-2xl font-black">{title}</h2><div className="mt-5 grid gap-3">{items.map(i=><div key={i} className="rounded-2xl bg-academy-surface p-4 leading-7 text-academy-muted ring-1 ring-academy-line">{i}</div>)}</div></div></div></section></VisualSection>}

export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const f=bts.find(x=>x.slug.endsWith(slug));if(!f)notFound();return <><Hero badge="BTS en alternance" title={f.title} subtitle={f.desc} actions={<><Button href="/contact">Candidature</Button><Button href="/financements/alternance" variant="secondary">Financement alternance</Button><Button href="/contact" variant="ghost">Demande d’informations</Button></>} visual={<BtsAlternanceVisual/>}/><VisualSection tone="bts"><section className="mx-auto max-w-7xl px-4 py-10"><div className="grid gap-4 md:grid-cols-3"><FeatureCard title="Durée">{f.duration}</FeatureCard><FeatureCard title="Public concerné">{f.audience}</FeatureCard><FeatureCard title="Prérequis">{f.prerequisites}</FeatureCard><FeatureCard title="Lieu">{f.locations}</FeatureCard><FeatureCard title="Financement">{f.financing}</FeatureCard><FeatureCard title="Certification">{f.certification}</FeatureCard></div><TrainingPathVisual tone="bts"/></section></VisualSection><ListSection title="Présentation" items={[f.desc]}/><ListSection title="Objectifs" items={f.objectives}/><ListSection title="Programme détaillé" items={f.program}/><ListSection title="Missions en entreprise" items={f.missions}/><ListSection title="Modalités d’évaluation" items={f.evaluation}/><ListSection title="Débouchés" items={f.outcomes}/><ListSection title="Qualités attendues" items={f.qualities}/><section className="px-4 py-10"><SectionTitle title="FAQ"/><FAQ items={f.faq}/></section></>}
